---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal-backoffice-qa
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/london-bridge/portal_backoffice-config
    targetRevision: main
    path: environments/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: portal-backoffice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
