---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  labels:
    secrets-store.csi.k8s.io/managed: "true"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibGJwYXktc3ZjLXVzZXIiLCJwYXNzd29yZCI6ImdocF9hRzJxdVB2OUFSYXVmY3Y3anU3bjQwdWliTk1peFIxZThMTHMiLCJhdXRoIjoiYkdKd1lYa3RjM1pqTFhWelpYSTZaMmh3WDJGSE1uRjFVSFk1UVZKaGRXWmpkamRxZFRkdU5EQjFhV0pPVFdsNFVqRmxPRXhNY3c9PSJ9fX0=
