---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: portal-backoffice-secrets
  labels:
    app.kubernetes.io/name: portal-backoffice
    app.kubernetes.io/part-of: portal-backoffice
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: portal-backoffice-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: /portal-backoffice/dev/manual-secrets
        conversionStrategy: Default
        decodingStrategy: None
