---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: portal-backoffice-secrets-class
  labels:
    app.kubernetes.io/name: portal-backoffice
    app.kubernetes.io/part-of: portal-backoffice
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "github-container-registry"
        objectType: secretsmanager
        jmesPath:
          - path: dockerconfigjson
            objectAlias: ghcr-config-json
  secretObjects:
    # Secret para imagePullSecrets (necessário para o Kubelet)
    - secretName: ghcr-secret
      type: kubernetes.io/dockerconfigjson
      data:
        - key: .dockerconfigjson
          objectName: ghcr-config-json
