---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-backoffice-sa
  labels:
    app.kubernetes.io/name: portal-backoffice
    app.kubernetes.io/part-of: portal-backoffice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::333449929724:role/secrets-manager-portal-backoffice
